- name: Wipe
  tags: [wipe]
  block:
    - name: Stop all Docker services
      ansible.builtin.docker_compose:
        project_src: "{{ web_app_path }}"
        state: absent
        remove_volumes: true
      ignore_errors: true

    - name: Remove app content
      file:
        state: absent
        dest: "{{ web_app_path }}"
