# https://docs.technotim.live/posts/grafana-loki/
# https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460
---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            log:
            stream:
            attrs:
            tag: attrs.tag
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - regex:
          expression: ^(?P<image_name>([^|]+))\|(?P<container_name>([^|]+))$
          source: "tag"
      - labels:
          tag:
          stream:
          image_name:
          container_name:
          image_id:
          container_id:
      - match:
          # drop all logs for all containers that don't have --log-opt: tag: "{{:ImageName}}|{{:Name}}"
          selector: '{job="docker",container_name="",image_name=""}'
          action: drop
      - output:
          source: log