password: ENC[AES256_GCM,data:nyN24YkosnZsWw==,iv:JeoxywJkK0CberYyzEl1zB07gz7atpCFtjX6FzM1F80=,tag:mHNz004QuD9RaPW+8WAZIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-14T12:10:20Z"
    mac: ENC[AES256_GCM,data:PXDJRaXr4mCBmGlF/gJ7xxxE3rQhNCaNF+JSt4r1fkeceaY5jE1wlR1+hoW/gKxuc1ufLJDej3i0UifHpXx25/yzH50MhWDZKeUB5IyLT5CKPoDlFiZJwPupHng5A2Zwd8RTmt5lhIx/THL93ZTsx7vTHDU0M9Le8lnHpjWo88A=,iv:zJHTUVsNHicOGS6sEmym1dH7qzPhIaA2PtI1Yreb6Yw=,tag:mo2DZaOfM8tZvGSCfkfLWQ==,type:str]
    pgp:
        - created_at: "2022-11-14T12:07:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DfKLzG8mZjyUSAQdA/3LObhc4CUEmmCdB+fCbu6T99cE8EVMMdU06q9zWSSww
            n+fv49ZMyRGK4wR9YEleTNYmyFn1mI+q+IcF7bFGgogokhbz9blPF402cTbxfbso
            1GYBCQIQ0p9DD2IsfZTXw9vdssuamXU6WJgwRNZU9uWGHwWaqVYBCU39zENKFnAQ
            4d/VPKNmLqiJxqrR4Y23BucEhbNyYQA2RRqVWRd7ZjXKb1NJNzyRIHkygB/qqGeq
            vOi3g1maWpM=
            =qSP5
            -----END PGP MESSAGE-----
          fp: 02981B278591A1936F1AA0A8B19A8B40F53E155F
    unencrypted_suffix: _unencrypted
    version: 3.7.3
